version: '3.8'
services:
    index:
        container_name: express_container
        image: express_image
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3000:3000"